here[build]
  publish = "/"

# توجيه طلبات الـ API
[[redirects]]
  from = "/api.php"
  to = "https://vay.rf.gd/public_html/api.php"
  status = 200
  force = true

# توجيه طلبات الجلسات
[[redirects]]
  from = "/session_init.php"
  to = "https://vay.rf.gd/public_html/session_init.php"
  status = 200
  force = true

# لجعل التوجيه (Routing) يعمل في تطبيقات الصفحة الواحدة (SPA) إذا لزم الأمر
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
